[package]
name = "krypton"
version = "0.1.0"
authors = ["infernalfire72"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-rt = "1"
bytes = "0.5.4"
rand = "0.7.3"
mysql = "*"
bcrypt = "0.6.2"